[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  NODE_ENV = "development"

[[plugins]]
  package = "@netlify/plugin-nextjs"